### ISSUE TITLE
no jQuery version

### ISSUE THREAD

**Issue by hustcc** [JoelSutherland/GitHub-jQuery-Repo-Widget#21]
This repo is very nice. Very thx.
But my website has no jQuery, so I rewrite to [https://github.com/hustcc/GitHub-Repo-Widget.js](https://github.com/hustcc/GitHub-Repo-Widget.js)

I hava done:
1. Rewrite `GitHub-jQuery-Repo-Widget`, and remove jQuery, then get `GitHub-Repo-Widget.js`. `Do not depends on jQuery or Other`.
2. Compress the image, then compress the file size. from `7.62kb` to `5.41kb`.
3. Update demo/index.html and screenshot.png.

thanks for you recommendation.

**Comment by cassiopaia** [comment]
link seems not to be working anymore .. can u share again ?

**Comment by hustcc** [comment]
@cassiopaia because some reason, all projects have been deleted. very sorry. 
I push again, please visit it again.

[https://github.com/hustcc/GitHub-Repo-Widget.js](https://github.com/hustcc/GitHub-Repo-Widget.js)
